name: Development build

on:
  [push, workflow_dispatch]

jobs:
  build:
    name: Development build
    runs-on: MacStadium
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout repository submodules
        run: git submodule update --init --recursive
        
      - name: Build packages
        env:
          password: ${{ secrets.ELLIE_MINI_SECRET }}
        run: |
          export NOSTDIN=1 SUDOPASS=$password
          export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
          gmake -j$(sysctl -n hw.ncpu) ipa

      - name: Upload regular artifact
        uses: actions/upload-artifact@v2
        with:
          name: net.kdt.pojavlauncher.development_iphoneos-arm.deb
          path: artifacts/net.kdt.pojavlauncher.*_iphoneos-arm.deb

      - name: Upload rootless artifact
        uses: actions/upload-artifact@v2
        with:
          name: net.kdt.pojavlauncher.development-rootless_iphoneos-arm.deb
          path: artifacts/net.kdt.pojavlauncher.*_iphoneos-arm64.deb

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v2
        with:
          name: net.kdt.pojavlauncher.ipa
          path: artifacts/net.kdt.pojavlauncher-*.ipa

      - name: Upload PojavLauncher.dSYM
        uses: actions/upload-artifact@v2
        with:
          name: PojavLauncher.dSYM
          path: artifacts/PojavLauncher.dSYM
          
      - name: Remove repository from runner
        env:
          password: ${{ secrets.ELLIE_MINI_SECRET }}
        run: |
          echo $password | sudo -S rm -rf /Users/administrator/Desktop/actions/actions-runner/_work/PojavLauncher_iOS
          echo $password | sudo -S rm -rf /Users/administrator/Desktop/actions/actions-runner-2/_work/PojavLauncher_iOS
          echo $password | sudo -S rm -rf /Users/administrator/Desktop/actions/actions-runner-3/_work/PojavLauncher_iOS
          echo $password | sudo -S rm -rf /Users/administrator/Desktop/actions/actions-runner-4/_work/PojavLauncher_iOS
          
