name: Release build

on:
  workflow_dispatch

jobs:
  build:
    name: Release build
    runs-on: macOS-11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout repository submodules
        run: git submodule update --init --recursive
        
      - name: Build packages
        run: |
          export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
          export PATH=/opt/procursus/bin:$PATH
          gmake -j$(sysctl -n hw.ncpu) ipa

      - name: Upload regular artifact
        uses: actions/upload-artifact@v2
        with:
          name: net.kdt.pojavlauncher.release_iphoneos-arm.deb
          path: artifacts/net.kdt.pojavlauncher.*_iphoneos-arm.deb
          
      - name: Upload rootless artifact
        uses: actions/upload-artifact@v2
        with:
          name: net.kdt.pojavlauncher.release-rootless_iphoneos-arm.deb
          path: artifacts/net.kdt.pojavlauncher.*_iphoneos-arm64.deb

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v2
        with:
          name: net.kdt.pojavlauncher-INT.ipa
          path: artifacts/net.kdt.pojavlauncher-*.ipa

      - name: Upload PojavLauncher.dSYM
        uses: actions/upload-artifact@v2
        with:
          name: PojavLauncher.dSYM
          path: artifacts/PojavLauncher.dSYM
          
